apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: one-gig
  containers:
  - name: tomcat-server
    image: tomcat:8
    volumeMounts:
    - mountPath: /data
      name: data
