kind: Pod
apiVersion: v1
metadata: 
  name: alpine
spec:
  containers:
    - name: alpine-container
      image: alpine
      command: ["sleep", "1d"] # Keep the container running
      resources:
        limits:
          memory: "30Mi"
          cpu: "200m"
        requests:  
          memory: "20Mi"
          cpu: "100m"
